[client]
enabled = true
address = "0.0.0.0"
port = 8091

[auth]
enabled = true
address = "0.0.0.0"
port = 8092

[agent]
socket = "/var/run/dstack.sock"
gateway_domain = "fixed/127.0.0.1:443"

[tls]
cert_file = "/etc/ssl/certs/server.crt"
key_file = "/etc/ssl/private/server.key"
ca_file = "/etc/ssl/certs/ca.crt"
