services:
  dstack-mesh:
    image: kvin/dstack-mesh
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock:ro
      - /dstack:/dstack
    ports:
      - "443:443"
    environment:
      - BACKEND=backend-app:8080
    restart: unless-stopped

  backend-app:
    image: node:18-alpine
    container_name: backend-app
    restart: unless-stopped
    command: >
      node -e "
      const http = require('http');
      const server = http.createServer((req, res) => {
        const appId = req.headers['x-dstack-app-id'] || 'unknown';
        const message = `Your app_id is: $${appId}`;
        res.writeHead(200, {'Content-Type': 'text/plain'});
        console.log(message);
        res.end(message);
      });
      server.listen(8080, '0.0.0.0');
      "

  test-client:
    image: alpine
    container_name: test-client
    depends_on:
      - dstack-mesh
      - backend-app
    command: |
      sh -c '
        apk add --no-cache curl jq
        sleep 2
        APP_ID=$$(curl -s http://dstack-mesh/info | jq -r .app_id)
        curl -s -H "x-dstack-target-app: $$APP_ID" http://dstack-mesh/
        echo ""
        echo "Sidecar tests completed..."
      '

