services:
  dstack-service:
    image: kvin/dstack-service@sha256:bc8288830006961bbbc797c71b4d84b11704f811d48d3b4efedb3cba31af497f
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VPC_SERVER_ENABLED=true
      # TODO: switch to VPC_ALLOWED_APPS=, but currently phala cloud has trouble with upgrading placeholder image
      - VPC_ALLOWED_APPS=any