services:
  dstack-service:
    image: kvin/dstack-service@sha256:f74b8434303211663c4d0826c28a56c93f369927a916ebd3fd43d43de6f05171
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VPC_SERVER_ENABLED=true
      - VPC_METRICS_ENABLED=true
      - VPC_ALLOWED_APPS=${VPC_ALLOWED_APPS}